import { useMemo, useRef } from "react";
import { useFrame } from "@react-three/fiber";
import type * as THREE from "three";
import { Waggonway } from "../components/Environment/Waggonway";
import { MineWorkings } from "../components/Environment/MineWorkings";
import { ChaldronWagon } from "../components/Train/ChaldronWagon";
import { Horse } from "../components/People/Horse";
import { Person, type NpcMotion } from "../components/People/Person";
import { createRng, makeOutfit, type Outfit } from "../components/People/npcStyle";
import { sampleShots, type Shot, type CameraShotResult } from "../components/Camera/shotUtils";
import { timelineStore } from "../state/timelineStore";
import { getScene, getSceneLocal, clamp01 } from "../timeline/timeline";

/** Where the loaded wagon stands while it is being filled, just clear of the adit mouth. */
const WAGON_START_Z = 6.5;
/** The horse is hitched this far ahead of the wagon body, down the line. */
const HITCH_AHEAD = 2.95;
/** The hauler leans into the collar here, and the wagon is under way a couple of seconds later. */
export const PULL_START = 6;
const PULL_RAMP = 2.5;
/** A loaded chaldron at a horse's walking pace. */
const HAUL_SPEED = 1.15;

/**
 * Metres the wagon has rolled at `local` — one eased pull away from standing, then a steady walk.
 * The ramp is the exact integral of a smoothstep on *speed* (∫ 3u²-2u³ = u³ - u⁴/2), so speed leaves
 * zero and reaches the walking pace with no step in either — a heavy load cannot jerk into motion,
 * and the audio, which differentiates this, would hear it as a bang if it did.
 */
export function wagonDistance(local: number): number {
  const t = local - PULL_START;
  if (t <= 0) return 0;
  if (t < PULL_RAMP) {
    const u = t / PULL_RAMP;
    return HAUL_SPEED * PULL_RAMP * (u * u * u - (u * u * u * u) / 2);
  }
  return HAUL_SPEED * PULL_RAMP * 0.5 + HAUL_SPEED * (t - PULL_RAMP);
}

/** 0 standing .. 1 walking, for the horse and the man at its head. */
function haulWalk(local: number): number {
  return clamp01((local - PULL_START + 0.8) / 1.4);
}

/** Metres of travel between hoofbeats: a walk puts down four feet per stride. */
const HOOF_SPACING = 1.7 / 4;

/**
 * Hoofbeats, generated by walking the very same `wagonDistance` the picture is driven by rather than
 * by hand-timing a list — so the sound cannot drift from the legs on screen the way a separate list
 * would once the pull timings are touched.
 */
export const EARLY_RAIL_HOOF_TIMES: number[] = (() => {
  const times: number[] = [];
  let next = HOOF_SPACING;
  // Stop at the scene span: choreography past it is never reached, so cues past it would never fire.
  for (let t = PULL_START; t <= getScene("earlyRail").designSpan; t += 1 / 60) {
    if (wagonDistance(t) >= next) {
      times.push(t);
      next += HOOF_SPACING;
    }
  }
  return times;
})();

interface CrewMember {
  key: string;
  outfit: Outfit;
  pos: [number, number, number];
  yaw: number;
  activity: "idle" | "shovel" | "chat" | "holdPole";
  phase: number;
}

/** The shift on the bank: two filling the wagon, one at the shaft, one watching from the adit mouth. */
function MineCrew() {
  const crew = useMemo<CrewMember[]>(() => {
    const rng = createRng(7);
    const spots: { pos: [number, number, number]; yaw: number; activity: CrewMember["activity"] }[] = [
      // Filling the wagon from the heap beside it, facing across the track.
      { pos: [-1.75, 0, 6.1], yaw: Math.PI / 2 - 0.25, activity: "shovel" },
      { pos: [-1.95, 0, 7.5], yaw: Math.PI / 2 - 0.1, activity: "shovel" },
      // At the shaft collar, taking a corf off the rope.
      { pos: [-5.1, 0, 8.4], yaw: -1.1, activity: "idle" },
      { pos: [-5.5, 0, 9.6], yaw: 0.6, activity: "chat" },
      // In the mouth of the adit, about to go back in.
      { pos: [1.15, 0, 13.6], yaw: 2.6, activity: "idle" },
      // Warming their hands at the brazier.
      { pos: [3.35, 0, 5.1], yaw: -1.9, activity: "idle" },
    ];
    return spots.map((s, i) => ({ key: `m${i}`, outfit: makeOutfit("mine", rng), ...s, phase: rng() * 40 }));
  }, []);

  return (
    <group>
      {crew.map((m) => (
        <Person key={m.key} outfit={m.outfit} position={m.pos} yaw={m.yaw} activity={m.activity} phase={m.phase} />
      ))}
    </group>
  );
}

/** The hauler walking at the horse's head, rein hand up, keeping pace with the load. */
function Hauler({ distanceRef, walkRef }: { distanceRef: React.MutableRefObject<number>; walkRef: React.MutableRefObject<number> }) {
  const outfit = useMemo(() => makeOutfit("mine", createRng(19)), []);
  const motion = useRef<NpcMotion>({ walk: 0, stride: 0 });

  useFrame(() => {
    motion.current.walk = walkRef.current;
    motion.current.stride = (distanceRef.current / 1.4) * Math.PI * 2;
  });

  return <Person outfit={outfit} motionRef={motion} activity="holdPole" phase={13} yaw={Math.PI} />;
}

/**
 * Scene 1 — a colliery waggonway, a century and a half before anything with a boiler. A loaded
 * chaldron wagon stands on wooden rails at the mouth of the adit while the shift fills it; a horse
 * is put to the traces and walks it away down the line, and the viewer walks alongside, ending low
 * and close to the rails themselves — the part of all this that actually lasted.
 */
export function EarlyRailScene() {
  const distanceRef = useRef(0);
  const walkRef = useRef(0);
  const haulGroupRef = useRef<THREE.Group>(null);

  useFrame(() => {
    const local = getSceneLocal(timelineStore.getElapsed()).local;
    distanceRef.current = wagonDistance(local);
    walkRef.current = haulWalk(local);
    // Wagon, horse and hauler are one rigid train, moved together down -Z.
    if (haulGroupRef.current) haulGroupRef.current.position.z = WAGON_START_Z - distanceRef.current;
  });

  return (
    <>
      <Waggonway />
      <MineWorkings />
      <MineCrew />

      {/* The heap the wagon is being filled from */}
      <mesh position={[-2.6, 0.38, 6.8]} rotation={[0, 0.7, 0]} castShadow receiveShadow>
        <coneGeometry args={[1.25, 0.95, 8]} />
        <meshStandardMaterial color="#141418" roughness={0.65} metalness={0.1} />
      </mesh>

      <group ref={haulGroupRef}>
        <ChaldronWagon distanceRef={distanceRef} lamp />
        <Horse distanceRef={distanceRef} walkRef={walkRef} position={[0, 0, -HITCH_AHEAD]} yaw={Math.PI} scale={0.95} harness />
        <group position={[-1.05, 0, -HITCH_AHEAD - 0.5]}>
          <Hauler distanceRef={distanceRef} walkRef={walkRef} />
        </group>
      </group>

      {/* A second, empty wagon standing on the short siding, waiting its turn at the heap */}
      <group position={[3.15, 0, 9.4]} rotation={[0, 0.06, 0]}>
        <ChaldronWagon load={0} />
      </group>
    </>
  );
}

const SHOTS: Shot[] = [
  { t: 0, pos: [2.05, 1.67, 10.4], look: [-0.2, 1.05, 6.6] }, // on the bank, watching the wagon being filled
  { t: 4, pos: [1.95, 1.66, 9.4], look: [-0.3, 1.1, 6.2] },
  { t: 6.5, pos: [1.85, 1.66, 8.2], look: [-0.15, 1.2, 3.8] }, // the horse is put to, the chain comes tight
  { t: 10, pos: [1.7, 1.64, 5.2], look: [0, 1.0, 2.2] }, // walking alongside as it gets under way
  { t: 13.5, pos: [1.5, 1.62, 1.2], look: [-0.05, 0.95, -1.8] },
  { t: 16, pos: [1.2, 1.2, -1.9], look: [-0.25, 0.55, -7] }, // crouching in toward the track
  { t: 18, pos: [0.95, 0.82, -3.4], look: [-0.4, 0.28, -26] }, // and down the wooden rails, out of sight
];

export function earlyRailShot(local: number): CameraShotResult {
  return sampleShots(local, SHOTS);
}
